Algoritmo "Escolha"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : rodrigormjo
// Data atual  : 24/4/2022
Var
// Seção de Declarações das variáveis
voto: caracter

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
Escreval("Escolha seu candidato")
Leia(voto)

Escolha voto
caso "20"
   Escreval("Você votou em Fulano.")
caso "31"
   Escreval("Você votou em Beutrano.")
caso "42"
   Escreval("Você votou em Ciclano.")
caso "171"
   Escreval("Você votou em Macaco Tião.")
outrocaso
   Escreval("Voto nulo.")
fimescolha

Fimalgoritmo