Algoritmo "Exercicios - Enquanto"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 24/4/2022
Var
// Seção de Declarações das variáveis
qtdeDasPessoas, maisNovo, MaisVelho: inteiro
mediaIdade, porcentagemMenorIdade: real

porcentagem



Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo