Algoritmo "Menu"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : rodrigormjo
// Data atual  : 24/4/2022
Var
// Seção de Declarações das variáveis
opcaoMenu: caracter


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
Escreval("1 - Troca de Óleo")
Escreval("2 - Balanceamento")
Escreval("3 - Sair")
leia(opcaoMenu)




Fimalgoritmo