Algoritmo "Para..."
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : rodrigormjo
// Data atual  : 24/4/2022
Var
// Seção de Declarações das variáveis
rng, i: inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
para i de 1 ate 50 passo 1 faca
     aleatorio 1, 20
        leia(rng)
     aleatorio off
     // escreval(rng)
fimpara

Fimalgoritmo