Algoritmo "Tabela Verdade"
//  
//  
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : rodrigormjo
// Data atual  : 24/4/2022
Var
// Seção de Declarações das variáveis 
afirmacao: logico
i, j: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
i <- 9
j <- 20

se (i = 10) OU (j = 20) entao
   Escreval("proc")
   senao
   Escreval("error")
fimse

Fimalgoritmo