Algoritmo "tiposDeVariáveis"
//  
//  
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : rodrigormjo
// Data atual  : 23/4/2022
Var
// Seção de Declarações das variáveis
   nome, sobrenome, nomeCompleto: caracter
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreval("Informe seu nome:")
   Leia(nome)
   Escreval("Informe seu sobrenome:")
   Leia(sobrenome)
   nomeCompleto <- nome + " " + sobrenome
   Escreval(nomeCompleto)

Fimalgoritmo
