Algoritmo "trabalhandoComTipos"
//  
//  
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : rodrigormjo
// Data atual  : 23/4/2022
Var
// Seção de Declarações das variáveis
   palavra1, palavra2, palavra3: caracter
   numero1, numero2, numero3: inteiro
   
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreval("Palavra1")
   Leia(palavra1)
   Escreval("Palavra2")
   Leia(palavra2)
   Escreval("numero1")
   Leia(numero1)
   Escreval("numero2")
   Leia(numero2)
   palavra3 <- palavra1 + palavra2
   numero3 <- numero1 - numero2
   Escreval(palavra3)
   Escreva(numero3)
Fimalgoritmo
