Algoritmo "trabalhandoComTipos2"
//  
//  
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : rodrigormjo
// Data atual  : 23/4/2022
Var
// Seção de Declarações das variáveis
    numero1, numero2, soma, subtracao, multiplicacao: inteiro
    divisao: real
    sucesso: logico
   
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreval("numero1")
   leia(numero1)
   Escreval("numero2")
   sucesso <- numero1 > 10
   leia(numero2)
   soma <- numero1 + numero2
   subtracao <- numero1 - numero2
   multiplicacao <- numero1 * numero2
   divisao <- numero1 / numero2
   
Fimalgoritmo
