Algoritmo "Vetores"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : rodrigormjo
// Data atual  : 25/4/2022
Var
// Seção de Declarações das variáveis
nomes: vetor[1..5] de caractere
vetorIdades: vetor[1..5] de inteiro
i: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
para i de 1 ate 5 faca
  escreval("Informe seu nome ", i, ":")
  leia(nomes[i])
fimpara
limpatela
para i de 1 ate 5 faca
  escreval(nomes[i])
fimpara


Fimalgoritmo